### ISSUE TITLE
How I use this rule ?

### ISSUE THREAD

**Issue by Javakky-pxv** [olafurpg/named-literal-arguments#1]
I have started to use scalafix in my project.
I found this rule in the [developer guide](https://scalacenter.github.io/scalafix/docs/developers/tutorial.html).
It is a excellent rule and I wanted to use it in my project, but I couldn't find it in [Built-in Rules](https://scalacenter.github.io/scalafix/docs/rules/overview.html) or [maven central repository](https://mvnrepository.com/artifact/com.geirsson).
Is there any plan to make this repository public? Also, how can I use it without copying it to my project directory?

**Comment by olafurpg** [comment]
Thank you for reporting! This rule is only created as documentation for the developer guide, it's not intended to be consumed. There are no plans to change that. Feel free to fork the project and release the code yourself if you want to use it in your codebase.
